name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - "container/**"
        
defaults:
  run:
    working-directory: container
    
jobs:
  deploy:
    name: Upload Container to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Build
        run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::691474667905:role/GithubActions
          aws-region: us-east-2
      - name: Sync Files to S3
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/container/latest/index.html"
